defaultPortal: sandbox
portals:
  - name: live
    portalId: 9073261
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLuLw9WjMBIIAAUAAAAAAAwY7eSpBCCZjdsMKO7pDDIUgW0DWDW5OUNrjDLVPgkHrsb6MCI6IQAABEEAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAPEIUy7OezKyunM_CNo6GISBH7kBbTGJKA25hMVIAWgA
        expiresAt: '2022-07-26T13:27:19.742Z'
    personalAccessKey: >-
      CiQzOTQyMWFiMi1kMTgzLTQ4MjItYmZiYy03NmY5NzU2OWI4MWIQ7eSpBBiZjdsMKhkABeaRglCArL1wiqDfmhdELfg7xSiEwh9JSgNuYTE
  - name: sandbox
    portalId: 25385250
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COK-tpHeLxIJAAkAAAAA4A0DGKKyjQwgmY3bDCju6QwyFKBXfxILrvoonT8ijNXTWTVAtqtMOigAAABBAAAAeAAAAAAAAAAAAAAAAAAAAAAAAMAHAP7_MTwAAAYAAABgQhRWKL7LAzPwo0R05XFuyf2Z_nmJgEoDZXUxUgBaAA
        expiresAt: '2021-12-22T12:46:20.520Z'
    personalAccessKey: >-
      CiRldTEtNDIyZi1jMTE4LTQ4N2EtOTk5YS0xZjYyOTk2ODJkOGUQorKNDBiZjdsMKhkABeaRghruWXENGY07uwqbtxH7YB9NgDL0SgNldTE
